default: true

# Line length - https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length
MD013:
  code_blocks: false
  tables: false

# Do not enforce line length in markdown files
line_length: false