body:
  - attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: Bug Report Checklist
      options:
        - label: I have pulled the latest `main` branch of the repository.
          required: true
    type: checkboxes
  - attributes:
      description: What did you expect to be able to do? Please describe the problem you are trying to solve.
      label: Overview
    type: textarea
    validations:
      required: true
  - attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
    type: textarea
description: Request that a new feature be added or an existing feature improved
labels:
  - "type: feature"
name: 🚀 Feature
title: "🚀 Feature: <short description of the feature>"